/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus')['ElButton']
    ElConfigProvider: typeof import('element-plus')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus')['ElDatePicker']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElInput: typeof import('element-plus')['ElInput']
    ElMenu: typeof import('element-plus')['ElMenu']
    ElMenuItem: typeof import('element-plus')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus')['ElSubMenu']
    ElSwitch: typeof import('element-plus')['ElSwitch']
    ElTag: typeof import('element-plus')['ElTag']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
  }
}
